### ISSUE TITLE
Add ARRAY support to PostgresqlReader

### ISSUE THREAD

**Issue by criccomini** [recap-build/recap#264]
Recap's PostgresqlReader does not currently support PG arrays as documented here:

https://www.postgresql.org/docs/current/arrays.html

The reader should be updated to support this type.

**Comment by criccomini** [comment]
Arrays in PG are tricky because they don't contain a type in information_schema.columns and they can have an arbitrary number of dimensions (int[] is not one dimensional; any number of dimensions can be stored in it).

https://www.postgresql.org/docs/current/arrays.html

**Comment by alexdemeo** [comment]
Hey Chris. I'm using recap and looking to leverage array functionality with postgres. I encountered this issue and had some questions about implementing this functionality. It seems it's possible to derive the innermost type of from `UDT_NAME` (slicing off the underscore prefix, eg: `"UDT_NAME": "_int4"`). Does that sound accurate? As far as the multidimensional array issue, do you see any path forward with still being able to add array support ambiguous to the dimensionality?

**Comment by criccomini** [comment]
Hi! I'll take a look at this tomorrow (hopefully). Spent all day fighting Hive and I'm out of gas now. :P

**Comment by criccomini** [comment]
Was reading over [this](https://www.postgresql.org/docs/current/infoschema-columns.html) just now.

> data_type character_data
> Data type of the column, if it is a built-in type, or ARRAY if it is some array (in that case, see the view element_types), ...

So the [`element_types`](https://www.postgresql.org/docs/current/infoschema-element-types.html) view seems promising. I'm curious how it handles multi-dimensional arrays, if at all. Need to poke around more.

**Comment by criccomini** [comment]
After Googling around a bit more, it still seems like there's no way to get the number of dimensions from ARRAY columns. And as you pointed out, UDT_NAME in the `columns` view has what we need for the types.

Next question is how to represent this in Recap. Maybe:

```yaml
type: list
name: baz
alias: foo.bar.Baz
values:
    - type: int32
    - type: foo.bar.Baz
```

This defines a list that can have either int32 (if the column has udf_name=_int4) or a list of the same. The cyclic reference makes it possible to have arbitrarily deep nesting as well as mixed lengths. I think this is what PG supports.

WDYT? The downside to this (IMO) is that it's pretty complex to deal with for the user. But it is actually what you can get from PG, so...

**Comment by alexdemeo** [comment]
I think this makes sense! It's unfortunate dimensionality isn't a part of the schema, but given that I agree cyclic reference is way to go. PG doesn't support mixed lengths within a particular dimension, but I don't think there's a good user-friendly way that represent that constraint.

**Comment by criccomini** [comment]
So, another observation. For types like `varchar(255)[]`, there's no way in PG to get the 255 octet length back. It allows you to define tables that way, but I don't think it's enforced?

**Comment by criccomini** [comment]
This is interesting, from ChatGPT:

![Screenshot 2023-12-20 at 11 38 25 AM](https://github.com/recap-build/recap/assets/167569/261bdb19-35ab-4376-add7-b06a66cc15d2)

I was wondering how PostgreSQL handles `bit(8)[]` columns. It sounds like it doesn't covert it to `bit varying[]` the way it does with VARCHAR. But it also doens't use `CHARACTER_MAXIMUM_LENGTH` the way `bit(8)` columns would.

**Comment by alexdemeo** [comment]
Oh interesting, it sounds like all this is actually doable with some edge-casing. We can also use `pg_attribute.attndims` to get the dimensionality. I guess it is stored, just not enforced.

**Comment by criccomini** [comment]
Here's my PR right now:

https://github.com/recap-build/recap/pull/410

I am not planning to implement the pg_attribute stuff right now. It just uses maximal defaults. If you want to submit a follow-on PR to add that support, you're welcome to. :)

**Comment by criccomini** [comment]
@alexdemeo recap-core 0.9.5 is on pypi with the latest changes for PostgreSQL arrays. Let me know if you have any issues with it. I'll try and update [the docs](https://recap.build/docs/integrations/postgresql/) this afternoon.
