### ISSUE TITLE
Expose statistics from the Schema Registry

### ISSUE THREAD

**Issue by cpard** [recap-build/recap#278]
Similarly to how hive metastore exposes statistics

**Comment by cpard** [comment]
yes, I think that the hive metastore stats are the minimum set of stats that are almost universally used. These statistics are big part of what goes in the query optimizers too. Just for clarity, these are the stats:

```
For a table:
row count: the total number of rows in the table

For each column in a table:
data size: the size of the data that needs to be read
nulls fraction: the fraction of null values
distinct value count: the number of distinct values
low value: the smallest value in the column
high value: the largest value in the column
```

Snowflake doesn't automatically expose these but it's pretty easy to define a view for these metrics and expose them if you need them. The question here is how Recap can accommodate this as there's no standardized interface as there is with the Hive metastore. 

Also, when it comes to statistics, the above are just the minimum set, there's a wealth of stats that can be shared for example, see [Load History](https://docs.snowflake.com/en/sql-reference/info-schema/load_history). This is important information for a data engineer. 

Although these might be already exposed through the integration of Recap with the Information schemas, I think there is value to offer a higher level model that is also curated towards the needs of OLAP workloads. 

Having said all the above, I totally agree with the overlay architecture that you propose and for stats in particular we can start with the minimum set of stats coming from HMS and we can carefully build on top for other systems.

**Comment by cpard** [comment]
Also regarding Iceberg, I'm pretty sure that Iceberg together with Hudi and Delta are exposing the information you see in the manifest files through a metastore. I don't think we need to write any manifest file parsers etc to get that information.

**Comment by criccomini** [comment]
Okay, I'm sold. Once we get metadata in https://github.com/recap-build/pymetastore for Hive, we can work on a *very* slim stats overlay for Recap. :) I think if it covers the most common stats from Hive Metastore, Iceberg, and the ones I calculated (see my link above), we should be good to start with. Adding is easier than subtracting later.

**Comment by criccomini** [comment]
Stats have been added to pymetastore https://github.com/recap-build/pymetastore/pull/25. NOTE: partition stats are still missing.

**Comment by criccomini** [comment]
I poked around a bit this afternoon. IMO the Hive stats are a good enough starting point.

A few things:

1. I want to do only column-level stats for now (not table or partition stats).
2. I want to keep the stats very minimal. Adding is later than removing.
3. I'm thinking we should store the stats in a `stats` sub-dict in the CST.

For (3), something like:

```yaml
---
type: struct
fields:
  - name: id
    type: int32
    stats:
      min: 1
      max: 1398
      nulls: 0
      distinct: 1398
      count: 1398
  - name: email
    type: string
    stats:
      min: 13
      max: 42
      avg: 16
      nulls: 43
      distinct: 1423
      count: 1423
```

Now, some notes:

### Hive

Leaving these here as notes so I can find them again:

* https://cwiki.apache.org/confluence/display/hive/statsdev
* https://devdoc.net/bigdata/hive-confluence-20210220/display/Hive/Column+Statistics+in+Hive.html

Some docs on Hive's stats.

### Iceberg

I took a look at Iceberg. They use [Puffin](https://iceberg.apache.org/puffin-spec/) files for stats, and I'm not 100% clear what's in them and if they're exposed via the REST catalog.

### Recap (legacy)

Here are the stats I was gathering for SQLAlchemy-compatible tables:

* https://github.com/recap-build/recap/blob/0.4.0/recap/analyzers/sqlalchemy/profile.py

### PostgreSQL

PG has a `pg_statistic` table that stores stats after `ANALYZE` [is run](https://www.postgresql.org/docs/current/sql-analyze.html). The stats `pg_statistic` columns are a [little weird](https://www.postgresql.org/docs/current/catalog-pg-statistic.html), but it has nulls (as a fraction of total), average width (in bytes), and distinct count.

**Comment by criccomini** [comment]
@cpard I was thinking about this a bit more last night. I'd been thinking of stats, validation, and DB constraints as "overlays" that live in the same CST as the schema. But, really, I think only constraints would need to live in the same CST (<, >, ==, contains). We could, for stats and DB constraints have a completely separate spec. Something like:

```yaml
type: table
name: some_table
columns:
  - name: id
    min: 1
    max: 1398
    nulls: 0
    distinct: 1398
    count: 1398
  - name: email
    min: 13
    max: 42
    avg: 16
    nulls: 43
    distinct: 1423
    count: 1423
```

This data model would be separate from the type spec data model.

Some thoughts:

1. In the combined ("overlay", as I've been calling it) style, I could see the schemas getting pretty complex looking if they had stats, constraints, etc.
2. The schema and stats sometimes come together (as with Hive Metastore). Separating the data models would probably mean separate read methods which would mean duplicate calls. Not a big deal, but it's something.
3. OTOH (re: (2)), most stats are separate calls (e.g. PG's `ANALYZE` and `pg_statistics` stuff). Combining the data models into one schema would require multiple calls to get the stats and stuff. Again, not a big deal, since we'd probably just have an `include_stats: bool = False` param.
4. The separate data model example I wrote above felt weird. It's very similar to the Recap type spec, but I made it a bit more specific to tables. Making it not identical to Recap's type spec feels weird, but making it different also feels weird. It feels most natural to include it as a `stats` overlay.

**Comment by cpard** [comment]
> @cpard I was thinking about this a bit more last night. I'd been thinking of stats, validation, and DB constraints as "overlays" that live in the same CST as the schema. But, really, I think only constraints would need to live in the same CST (<, >, ==, contains). We could, for stats and DB constraints have a completely separate spec. Something like:
> 
> ```yaml
> type: table
> name: some_table
> columns:
>   - name: id
>     min: 1
>     max: 1398
>     nulls: 0
>     distinct: 1398
>     count: 1398
>   - name: email
>     min: 13
>     max: 42
>     avg: 16
>     nulls: 43
>     distinct: 1423
>     count: 1423
> ```
> 
> This data model would be separate from the type spec data model.
> 
> Some thoughts:
> 
> 1. In the combined ("overlay", as I've been calling it) style, I could see the schemas getting pretty complex looking if they had stats, constraints, etc.
> 2. The schema and stats sometimes come together (as with Hive Metastore). Separating the data models would probably mean separate read methods which would mean duplicate calls. Not a big deal, but it's something.
> 3. OTOH (re: (2)), most stats are separate calls (e.g. PG's `ANALYZE` and `pg_statistics` stuff). Combining the data models into one schema would require multiple calls to get the stats and stuff. Again, not a big deal, since we'd probably just have an `include_stats: bool = False` param.
> 4. The separate data model example I wrote above felt weird. It's very similar to the Recap type spec, but I made it a bit more specific to tables. Making it not identical to Recap's type spec feels weird, but making it different also feels weird. It feels most natural to include it as a `stats` overlay.

Actually I would consider constraints a completely separated thing than statistics to be honest. It's a huge topic and one that has not been figured out yet imo. My suggestion is to leave constraints out of the conversation for now, we can start a conversation about this on a different thread.

Regarding statistics, I do agree on narrowing down the scope for now and not include partition stats. But, I do believe we should keep it on the table level. The column on its own does not have meaning without the context of the table. Also, the way the HMS is modeled, you can't really fetch column statistics without going through the table. The exposed interfaces are one for getting table statistics (which includes stats for each column) and partition statistics. I believe the reason they have these two interfaces is primarily because partitions can have additional filters on the values that create the partitioning. 

Partition statistics are important for data engineering imo, as partitioning is the many mechanism for optimizing the data lake. As they usually say in distributed OLAP, the best performance optimization is always to figure out ways to avoid reading the data completely and that's what partitioning offers here. I believe that there are partition operations that are important and that new tooling is needed but we should focus on that on a later iteration. 

I'm not so sure I understand completely the "overlay" concept, I might need a bit more color on this to have an opinion but I want to add another dimension to the problem. Statistics in general are not enforced and for a good reason, they tend to be expensive operations (e.g. measuring cardinalities). This means that statistics might not be present or that they might be stall etc. I believe there's wisdom in these choices all the db vendors have made so far to separate the schema read ops from the statistic ops. 

My initial reaction is that if the Recap type system can represent the stats, why not do some dogfooding here? But as I said, I need to understand the overlay concept a bit better. 

Also one final comment, on the example you gave, I would add some kind of information to make it almost too obvious that we are representing statistics here.

**Comment by criccomini** [comment]
> I do agree on narrowing down the scope for now and not include partition stats

👍 

> But, I do believe we should keep it on the table level.

👍 

> Partition statistics are important for data engineering imo

There's nothing stopping us from including partition stats in HiveMetastoreReader. It would just be ignored by standardized tooling (i.e. ignored from the standard Recap stats). Tools that *know* they're reading from Hive could expect to see the extra partition stuff.

And as you said, we can always add the partition stats later.

> I'm not so sure I understand completely the "overlay" concept

I just mean adding extra standardized fields to the Recap type data structure, similar to how JSON Schema has a separate [JSON Schema Validation](https://json-schema.org/draft/2020-12/json-schema-validation.html) spec that overlays on top of [JSON Schema Core](https://json-schema.org/draft/2020-12/json-schema-core.html).

The alternative would be to have two different data models that aren't related to each other: one for type spec (the current Recap type spec) and another for stats (e.g. a Recap stats spec).

This is the "overlay" style (i.e. what JSON schema does with their validations spec):

```yaml
type: struct
fields:
  - name: id
    type: int32
    stats:
      min: 1
      max: 1398
      nulls: 0
      distinct: 1398
      count: 1398
  - name: email
    type: string
    stats:
      min: 13
      max: 42
      avg: 16
      nulls: 43
      distinct: 1423
      count: 1423
```

And this is the alternative, a Recap stats spec (with no relation to Recap type spec's data model):

```yaml
type: table
name: some_table
columns:
  - name: id
    min: 1
    max: 1398
    nulls: 0
    distinct: 1398
    count: 1398
  - name: email
    min: 13
    max: 42
    avg: 16
    nulls: 43
    distinct: 1423
    count: 1423
```

>  I believe there's wisdom in these choices all the db vendors have made so far to separate the schema read ops from the statistic ops.

Yea, this is what I was saying before w.r.t. two separate reads.

> My initial reaction is that if the Recap type system can represent the stats, why not do some dogfooding here?

Yea, I'm inclined to go that way as well. The "safest" thing to do would be to have the `HiveMetastoreReader` include stats in its extra_attrs, and have no formalized stats spec. If we like it and find we can use the same fields for other readers (e.g. PostgresReader), we can then formalize it later.

**Comment by cpard** [comment]
ok now I get the overlay concept and I agree that an overlay a la JSON Schema feels much better than the alternative of having a Recap stats spec with no relation to the recap type spec.

**Comment by criccomini** [comment]
K, I'll move forward with a `stats` field in extra_attrs for the HiveMetastoreReader columns. :)

**Comment by criccomini** [comment]
@cpard random question: Can column stats be nested? That is, can a struct<> for example have stats for its subfields?

**Comment by criccomini** [comment]
Blocked by https://github.com/recap-build/pymetastore/issues/27

**Comment by cpard** [comment]
No, HMS supports stats for very specific column types, boolean, long,
decimal, dates, strings etc. even for them not all stats apply to all of
them.
