### ISSUE TITLE
Implement `RecapType.__dict__()` for all Recap types

### ISSUE THREAD

**Issue by criccomini** [recap-build/recap#289]
`recap.types` has `from_dict` to convert a Recap CST (dictionary) to a Recap AST (RecapType). We don't have an easy way to go the other direction, though.

As a developer, I'd like to be able to convert RecapTypes back to CST representations (in dictionary form) so I can serialize them to JSON, YAML, or TOML. This would be useful for a lot of use cases:

* A REST web service that returns Recap schemas in JSON form
* Tooling that builds and saves Recap types from other systems
* Transpilers that convert Avro/JSON Schema/Protos to Recap schemas

fyi @adrianisk

**Comment by criccomini** [comment]
@adrianisk 💥 Got this done. LMK if you run into any problems with it.

You should be able to use it to serialize RecapTypes to JSON, YAML, TOML, etc.

**Comment by adrianisk** [comment]
Nice! I'll check it out today
