### ISSUE TITLE
Add logical types to the spec tests

### ISSUE THREAD

**Issue by criccomini** [recap-build/recap#350]
The test_json_schema_spec.py test doesn't currently validate that logical types conform to their required attributes (e.g. `decimal` has `precision` and `scale` and is of type `bytes`). It probably should. The question is: how.

The most basic implementation would just validate the built-in logical types.

A more sophisticated version would validate other types. Unfortunately, we don't know what other (non-builtin) logical types might be defined. This is the whole point of logical types. I suppose we could make logical types pluggable such that Recap allowed you to define schemas, but this adds complexity, and I don't think it really adds any value aside from validation.

As such, I'm thinking just validating the builtin types is good enough.

Ranom thought: another way to think about this is as compile-time vs. runtime errors/validation. As long as the CST is parsable and conforms to the Recap spec, it's said to be (compile-time) valid. It makes no guarantees about the validity of logical types (and potentially alias references?). These would be considered runtime failures. This is a semantic distinction, but could let us get around this issue (and potentially strip  out the alias logic validation we currently have).

@mjperrone thoughts here?

**Comment by mjperrone** [comment]
I think validating the built-in logical types will be easy with a discriminated union, basically. Like I did [with RecapType.oneOf](https://github.com/recap-build/recap/blob/main/tests/0.2.0.json#L10)

I think it makes sense to validate as much as possible with the JSON Schema. I think there should be another more detailed validation process that covers correctness fully. I think each validation method should be clear about what it does and does not check for in documentation.

**Comment by criccomini** [comment]
SGTM!

**Comment by criccomini** [comment]
Closing as dupe of #350
